# Prueba de regresiones

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Importar los modelos propios
from random_forest_regression import RandomForestRegression
from xgboost_regression import XGBoostRegression

In [2]:
df = pd.read_csv("weatherHistory.csv")
display(df.head())

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [3]:
X_df = df.drop(columns=['Formatted Date', 'Temperature (C)', 'Apparent Temperature (C)','Summary', 'Precip Type', 'Daily Summary'])
y_df = df['Temperature (C)']

In [4]:
display(X_df.head())
display(y_df.head())

,Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
0,0.89,14.1197,251.0,15.8263,0.0,1015.13
1,0.86,14.2646,259.0,15.8263,0.0,1015.63
2,0.89,3.9284,204.0,14.9569,0.0,1015.94
3,0.83,14.1036,269.0,15.8263,0.0,1016.41
4,0.83,11.0446,259.0,15.8263,0.0,1016.51

0    9.472222
1    9.355556
2    9.377778
3    8.288889
4    8.755556
Name: Temperature (C), dtype: float64

In [5]:
# Random Forest Regression
rf_model = RandomForestRegression(tune = True)

In [6]:
rf_model.fit(X_df, y_df)

In [7]:
rf_model.print_metrics()

Métricas de prueba:
MSE: 29.0178
RMSE: 5.3868
MAE: 4.1650
R^2: 0.6851